cdrs/urls.py
from django.conf.urls import url
from .views import *
from archives.views import archive_cdrs_home

urlpatterns = [
   url(r'^cdrs/$', cdr_home),
   url(r'^cdrs/ajax/filter/$', cdr_items),
   url(r'^cdrs/changevalid/$', cdr_change_valid),
   url(r'^cdrs/export/excel/$', cdr_export_excel),
   #url(r'^cdrs/archives/(?P<archive_id>[0-9]*)$', archive_cdrs_home),
]

phonecab/urls.py
"""
General Url pattern
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
admin.autodiscover()

from phoneusers.urls import urlpatterns as phoneusers_urlpatterns
from prefs.urls import urlpatterns as prefs_urlpatterns
from cdrs.urls import urlpatterns as cdrs_urlpatterns
from records.urls import urlpatterns as records_urlpatterns
from profiles.urls import urlpatterns as profiles_urlpatterns
from audits.urls import urlpatterns as audits_urlpatterns
from archives.urls import urlpatterns as archives_urlpatterns
from tools.urls import urlpatterns as tools_urlpatterns
from logs.urls import urlpatterns as logs_urlpatterns

from phonecab.views import *

urlpatterns = [
    url(r'^$', phonecab_login),
    url(r'^login/$', phonecab_login),
    url(r'^logout/$', phonecab_logout),
    url(r'^phonecab/$', phonecab_realtime),
    url(r'^nightmode/$', phonecab_get_nightmode),
    url(r'^nightmode/(?P<mode>.*)$', phonecab_set_nightmode),

    url(r'^recordings/(?P<path>.*)$', serve,
        {'document_root': settings.RECORDS_ROOT}),

    url(r'^admin/doc/',
        include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += phoneusers_urlpatterns
urlpatterns += prefs_urlpatterns
urlpatterns += cdrs_urlpatterns
urlpatterns += records_urlpatterns
urlpatterns += profiles_urlpatterns
urlpatterns += audits_urlpatterns
urlpatterns += archives_urlpatterns
urlpatterns += tools_urlpatterns
urlpatterns += logs_urlpatterns

phoneusers/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^phoneusers/$', phoneuser_home),
    url(r'^phoneusers/new/$', phoneuser_edit),
    url(r'^phoneusers/view/(?P<phoneuser_id>[0-9]*)$', phoneuser_view),
    url(r'^phoneusers/edit/$', phoneuser_edit),
    url(r'^phoneusers/save/$', phoneuser_save),
    #url(r'^phoneusers/export/(?P<pincode>[0-9]*)$', phoneuser_export),
    url(r'^phoneusers/name/(?P<pincode>[0-9]*)$', phoneuser_name),
    url(r'^phoneusers/data/(?P<phoneuser_id>[0-9]*)$', phoneuser_data),
    url(r'^phoneusers/realtime/info/$', phoneuser_realtime_info),
    #url(r'^phoneusers/enable/(?P<phoneuser_id>[0-9]*)$', phoneuser_enable),
    #url(r'^phoneusers/disable/(?P<phoneuser_id>[0-9]*)$', phoneuser_disable),
    url(r'^phoneusers/changestatus/$', phoneuser_change_status),
    url(r'^phoneusers/check/pincode/$', phoneuser_check_pincode),
    url(r'^phoneusers/check/whitelist/$', phoneuser_check_whitelist),
    url(r'^phoneusers/archive/$', phoneuser_archive),
    url(r'^phoneusers/export/excel/$', phoneuser_export_excel),

    url(r'^whitelists/$', whitelist_items),
    url(r'^whitelists/edit/$', whitelist_edit),
    url(r'^whitelists/save/$', whitelist_save),
    url(r'^whitelists/remove/$', whitelist_remove),
    url(r'^whitelists/changestatus/$', whitelist_change_status),
    url(r'^whitelists/changeordinary/$', whitelist_change_ordinary),
    url(r'^whitelists/changeadditional/$', whitelist_change_additional),
    url(r'^whitelists/checkextra/$', whitelist_check_extra),
    #url(r'^whitelist/edit/(?P<whitelist_id>[0-9]*)$',
    # whitelist_edit),
    url(r'^credits/$', credit_items),
    url(r'^credits/new/$', credit_new),
    url(r'^credits/save/$', credit_save),
    url(r'^credits/print_recharge/(?P<credit_id>[0-9]*)$', credit_print_recharge),
    url(r'^credits/export/(?P<phoneuser_id>[0-9]*)$', credit_export),

]

phoneusers/models.py
import datetime
from django.db import models
from audits.models import Audit


class PhoneUser(models.Model):
    """
    Phoneuser

    Modella la scheda anagrafica.
    """

    ITALIAN = 'it'
    ENGLISH = 'en'
    FRENCH = 'fr'
    GERMAN = 'de'
    SPANISH = 'es'
    ARABIC = 'ar'

    LANGUAGES = (
        (ITALIAN, 'Italiano'),
        (ENGLISH, 'Inglese'),
        (FRENCH, 'Francese'),
        (GERMAN, 'Tedesco'),
        (SPANISH, 'Spagnolo'),
        (ARABIC, 'Arabo'),
    )

    STATO_NUOVO = 0
    STATO_IN_ATTESA = 1
    STATO_DEFINITIVO = 2

    STATI = (
        (STATO_NUOVO, 'nuovo arrivo'),
        (STATO_IN_ATTESA, 'in attesa di giudizio'),
        (STATO_DEFINITIVO, 'definitivo'),
    )

    first_name = models.CharField(max_length=35, verbose_name="nome")
    last_name = models.CharField(max_length=50, verbose_name="cognome")
    pincode = models.CharField(max_length=10, verbose_name="pin")
    serial_no = models.CharField(
        max_length=24, verbose_name="matricola", default='')
    listening_enabled = models.BooleanField(
        verbose_name="ascolto", default=False)
    recording_enabled = models.BooleanField(
        verbose_name="registrazione", default=False)
    covid_enabled = models.BooleanField(
        verbose_name="covid", default=False)
    enabled = models.BooleanField(verbose_name="stato", default=True)
    balance = models.DecimalField(
        verbose_name="credito residuo",
        default=0,
        max_digits=7,
        decimal_places=4)
    language = models.CharField(
        max_length=4, verbose_name="lingua", choices=LANGUAGES, default=ITALIAN)
    additional_calls = models.IntegerField(
        verbose_name="chiamate supplementari", default=0)
    additional_due_date = models.DateTimeField(
        verbose_name="scadenza chiamate supplementari", null=True)
    vipaccount = models.BooleanField(
        verbose_name="senza restizioni", default=False)
    four_bis_limited = models.BooleanField(
        verbose_name="4bis limitato", default=False)
    status = models.IntegerField(
        verbose_name="stato", choices=STATI, default=STATO_NUOVO)

    def get_full_name(self):
        return "%s %s" % (self.last_name, self.first_name)

    @staticmethod
    def get_from_pincode(pincode):
        items = PhoneUser.objects.filter(pincode=pincode)
        if items:
            return items[0]
        return None

    @staticmethod
    def get_from_serial_no(serial_no):
        items = PhoneUser.objects.filter(serial_no=serial_no)
        if items:
            return items[0]
        return None

    def __unicode__(self):
        return "%s %s (matricola %s codice %s)" % (self.last_name,
                                                   self.first_name,
                                                   self.serial_no,
                                                   self.pincode)


class Whitelist(models.Model):

    """
    Whitelist

    Modella i numeri che il phoneuser puo chiamare
    """

    ORDINARY_KIND = 0           # free
    SPECIAL_KIND = 1

    KINDS = (
        (ORDINARY_KIND, 'Ordinaria'),
        (SPECIAL_KIND, 'Primo ingresso'),
    )

    phoneuser = models.ForeignKey(PhoneUser)
    label = models.CharField(max_length=255, verbose_name="etichetta")
    phonenumber = models.CharField(max_length=40, verbose_name="telefono")
    duration = models.IntegerField(verbose_name="durata massima", default=600)
    kind = models.IntegerField(
        verbose_name="tipologia",
        choices=KINDS,
        default=ORDINARY_KIND)
    lawyer = models.BooleanField(
        verbose_name='avvocato',
        default=False)
    extraordinary = models.BooleanField(
        verbose_name='straordinaria',
        default=False)
    # definisce se un cellulare debba essere trattato come tale o come fisso
    real_mobile = models.BooleanField(
        verbose_name='cellulare',
        default=False)
    enabled = models.BooleanField(verbose_name="stato", default=False)
    additional = models.BooleanField(verbose_name="abilitazione a supplementari", default=False)

    def __unicode__(self):
        return "Numero %s (%s) relativo a %s" % (self.phonenumber,
            self.label,
            self.phoneuser,)


class Credit(models.Model):

    """
    Classe Credit

    Modella le ricariche effettuate dal phoneuser
    """
    phoneuser = models.ForeignKey(PhoneUser)
    recharge = models.DecimalField(
        verbose_name="ricarica", default=0, max_digits=5, decimal_places=2)
    recharge_date = models.DateTimeField(default=datetime.datetime.now)
    reason = models.CharField(max_length=255)

    @staticmethod
    def get_total(phoneuser):
        """Restituisce il totale delle ricariche effettuate"""
        total = Credit.objects.filter(phoneuser=phoneuser).aggregate(total=models.Sum('recharge'))
        return total['total']

templates/phoneusers/credit_modal.html
 <!-- ricariche modal -->
 <div id="ric-modal" style="padding:15px;">
    <div class="form-inline control-group" style="margin-bottom:10px;" id="credit-recharge-div">
        <label style="text-align: right; width: 100px;margin-right:2px;">Importo:</label>
            <input type="text" class="input-mini prependedInput" style="text-align: center;" placeholder="importo" name="recharge" id="credit-recharge"> &nbsp;&euro;
    </div>
    <div class="form-inline control-group" style="margin-bottom:10px;" id="credit-reason-div">
        <label style="text-align: right; width: 100px;margin-right:2px;">Causale:</label>
            <textarea rows="3" name="reason" id="credit-reason"></textarea>
    </div>
    <input type="hidden" name="phoneuser_id" id="credit-phoneuser-id" value="{{ phoneuser_id }}">
 </div>

templates/phoneusers/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}PhoneCab - Anagrafiche{% endblock %}
{% block stylesheet %}
{% endblock stylesheet %}
{% block application %}
<div class="page-header">
  {% if priv_anagrafica > 1 %}
  <button class="action btn btn-primary"
          onClick="Phoneuser.edit(0)"
          data-toggle="tooltip" type="button">
    <span class="zmdi zmdi-plus"></span> Nuova Anagrafica
    <div class="ripple-wrapper"></div>
  </button>
  {% endif %}

  <a href="/archives/phoneusers/" class="action btn btn-info" data-help="Mostra le anagrafiche archiviate">
    <span class="zmdi zmdi-chevron-right"></span> Archivio
    <div class="ripple-wrapper"></div>
  </a>
  <a href="/phoneusers/export/excel/" class="action btn btn-warning" data-help="Esporta le anagrafiche">
    <span class="zmdi zmdi-download"></span> Esporta
    <div class="ripple-wrapper"></div>
  </a>
  <h1><i class="zmdi zmdi-accounts"></i> Anagrafiche in corso</h1>
  <!-- <p class="lead">Lista delle anagrafiche in corso, con lo stato attuale della scheda e la possibilit&agrave; di esportazione dei dati</p> -->
</div>
<div class="card bordered">
    <div class="card-content">
        <form method="GET">
        <div style="float:right;">
                <button class="btn filtra btn-success phoneuser-do-filter"><i class="zmdi zmdi-flash"></i> Filtra</button>
                <a href="/phoneusers" class="btn filtra btn-info"><i class="zmdi zmdi-close"></i></a>
        </div>
        <span>
            <label>Cognome, Matricola o Codice&nbsp;</label>
            <input type="text" name="keyword" value="{{ d.keyword }}" maxlength="20" size="20" class="input-small">
        </span>
        <span>
            <label>Stato&nbsp;</label>
            <select name="enabled" style="width: 160px;">
                <option value=""{% if d.enabled == ""%} selected{% endif %}>Tutte</option>
                <option value="1"{% if d.enabled == "1"%} selected{% endif %}>Abilitate</option>
                <option value="0"{% if d.enabled == "0"%} selected{% endif %}>Disabilitate</option>
            </select>
        </span>

        </form>
        <div style="clear:both;"></div>
    </div>
    <div class="inner table" id="phoneusers">{{ phoneusers }}</div>
</div>
{% endblock application %}
{% block script %}
<script src="{% static "js/phoneuser.js" %}" type="text/javascript" charset="utf-8"></script>
{% endblock script %}

templates/phoneusers/page.html
{% extends "base.html" %}
{% load static %}
{% load phonecabtags %}
{% block title %}PhoneCab - Anagrafica{% endblock %}
{% block application %}
<div class="page-header">
  <h1><a href="/phoneusers/"><i class="zmdi zmdi-chevron-left zmdi-hc-lg" style="margin-right:10px;"></i></a><i class="zmdi zmdi-accounts"></i> Scheda Anagrafica</h1>
  <!--<p class="lead">Lista delle anagrafiche in corso, con lo stato attuale della scheda e la possibilit&agrave; di esportazione dei dati</p>-->
</div>

<div id="phoneuser">{{ phoneuser }}</div>

<!-- WHITELISTS -->
{% if priv_whitelist > 0 %}<div id="whitelists">{{ whitelists }}</div>{% endif %}
<!-- FINE WHITELISTS -->
<!-- CREDITS -->
{% if priv_credit > 0 %}<div id="credits">{{ credits }}</div>{% endif %}
<!-- FINE CREDITS -->
{% endblock application %}   
{% block script %}
     <script src="{% static "js/phoneuser.js" %}" type="text/javascript" charset="utf-8"></script>
{% endblock script %}    

templates/phoneusers/phoneuser.html
{% load static %}
{% load phonecabtags %}
<form class="form-horizontal placeholder-form" novalidate="true">
    <fieldset>
        <!--<legend>{{ form_title }} TEST</legend> <span class="help-block m-b-20">Please fill out the following form below.</span>-->
        <div class="form-group">
            <label for="enabled" class="col-xs-4 control-label">Scheda Attiva</label>
            <div class="col-xs-4">
                <div class="checkbox">
                    <label class="filled">
                        <input type="checkbox" {% if phoneuser.enabled %}checked="checked" {% endif %} id="enabled">
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Stato</label>
            <div class="col-xs-4">
                <select class="select2 form-control select2-hidden-accessible" tabindex="-1" aria-hidden="true" id="status">
                    <option value="0" {% if phoneuser.status == 0 %} selected{% endif %}>Nuovo arrivo</option>
                    <option value="1" {% if phoneuser.status == 1 %} selected{% endif %}>In attesa di giudizio</option>
                    <option value="2" {% if phoneuser.status == 2 %} selected{% endif %}>Definitivo</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="first-name" class="col-xs-4 control-label">Nome</label>
            <div class="col-xs-6 filled">
                <input type="text" class="form-control input-small" id="first-name" placeholder="Nome" value="{{ phoneuser.first_name }}" required>
            </div>
        </div>
        <div class="form-group">
            <label for="last-name" class="col-xs-4 control-label">Cognome</label>
            <div class="col-xs-6 filled">
                <input type="text" class="form-control" id="last-name" placeholder="Cognome" value="{{ phoneuser.last_name }}">
            </div>
        </div>
        <div class="form-group">
            <label for="serial-no" class="col-xs-4 control-label">Matricola</label>
            <div class="col-xs-3 filled">
                <input type="text" class="form-control" id="serial-no" placeholder="Matricola" value="{{ phoneuser.serial_no }}">
            </div>
        </div>
        <div class="form-group">
            <label for="pincode" class="col-xs-4 control-label">Codice Tessera</label>
            <div class="col-xs-3 filled">
                <input type="text" class="form-control" id="pincode" placeholder="Codice" value="{{ phoneuser.pincode }}" maxlength="10" {% if phoneuser.pincode and not user.is_staff %} readonly{% endif %}>
                <span class="pincode-check hide" style="color: red;">Gi&agrave; in uso</span>
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Lingua</label>
            <div class="col-xs-4">
                <select class="select2 form-control select2-hidden-accessible" tabindex="-1" aria-hidden="true" id="language">
                    <option value="it" {% if phoneuser.language == 'it' %} selected{% endif %}>Italiano</option>
                    <option value="en" {% if phoneuser.language == 'en' %} selected{% endif %}>Inglese</option>
                    <option value="fr" {% if phoneuser.language == 'fr' %} selected{% endif %}>Francese</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="four-bis-limited" class="col-xs-4 control-label">4 bis limitato</label>
            <div class="col-xs-8">
                <div class="checkbox">
                    <label class="filled">
                        <input type="checkbox" {% if phoneuser.four_bis_limited %}checked="checked" {% endif %} id="four-bis-limited">
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="additional_enabled" class="col-xs-4 control-label">Chiamate Supplementari</label>
            <div class="col-xs-8">
                <div class="checkbox">
                    <label class="filled">
                        <input type="checkbox" {% if phoneuser.additional_calls|to_int %}checked="checked" {% endif %} {% if change_additional_calls == 0 %} disabled{% endif %} id="additional-enabled" onclick="Phoneuser.handleAdditionalCalls(this);">
                    </label>
                </div>
            </div>
            <label for="additional-calls" class="col-xs-4 control-label">Numero</label>
            <div class="col-xs-1 filled">
                <input type="text" class="form-control" id="additional-calls" placeholder="" value="{{ phoneuser.additional_calls }}" {% if change_additional_calls == 0 or not phoneuser.id or not phoneuser.additional_calls %} disabled{% endif %}>
            </div>
            <label for="additional-duedate" class="col-xs-3 control-label">Fino al (escluso)</label>
                <input type="text" value="{{ phoneuser.additional_due_date|date:"d-m-Y" }}" maxlength="12" size="8" class="input-small datepicker" {% if change_additional_calls == 0 or not phoneuser.id or not phoneuser.additional_calls %} disabled{% endif %} id="additional-duedate">
        </div>
        <div class="form-group">
            <label for="listening_enabled" class="col-xs-4 control-label">Ascolto</label>
            <div class="col-xs-8">
                <div class="checkbox">
                    <label class="filled">
                        <input type="checkbox" {% if phoneuser.listening_enabled %}checked="checked" {% endif %} id="listening-enabled">
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="recording_enabled" class="col-xs-4 control-label">Registrazione</label>
            <div class="col-xs-8">
                <div class="checkbox">
                    <label class="filled">
                        <input type="checkbox" {% if phoneuser.recording_enabled %}checked="checked" {% endif %} id="recording-enabled">
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="recording_enabled" class="col-xs-4 control-label">Abilitazione COVID19</label>
            <div class="col-xs-8">
                <div class="checkbox">
                    <label class="filled">
                        <input type="checkbox" {% if phoneuser.covid_enabled %}checked="checked" {% endif %} id="covid-enabled">
                    </label>
                </div>
            </div>
        </div>
        <input type="hidden" id="phoneuser-id-modal" value="{{ phoneuser.id }}">
    </fieldset>
</form>

templates/phoneusers/phoneuser_data.html
{% load phonecabtags %}
<div class="card bordered">
    <div class="card-content">
        <div style="float: right;">
            <span class="label {{phoneuser.covid_enabled|to_int|yesno:" green,red"}}">
             <span class="zmdi-hc-stack zmdi-hc-lg">
                <i class="zmdi zmdi-alert-polygon zmdi-hc-stack-1x"></i>
                {% if phoneuser.covid_enabled|to_int == 0 %}
                <i class="zmdi zmdi-block zmdi-hc-stack-2x"></i>
                {% endif %}
            </span>
            Abilitazione COVID
            </span>
              &nbsp;&nbsp;
            <span class="label {{phoneuser.additional_calls|to_int|yesno:" green,red"}}">
              <span class="zmdi-hc-stack zmdi-hc-lg">
                <i class="zmdi zmdi-phone zmdi-hc-stack-1x"></i>
                {% if phoneuser.additional_calls|to_int == 0 %}
                <i class="zmdi zmdi-block zmdi-hc-stack-2x"></i>
                {% endif %}
              </span>
                Supplementari {% if phoneuser.additional_calls|to_int %} {% if phoneuser.additional_calls %} (fine: {{ phoneuser.additional_due_date|italian_date}}){% else %} a tempo indeterminato{% endif %}{% endif %}
            </span>
            &nbsp;&nbsp;
            <span class="label {{phoneuser.recording_enabled|yesno:" green,red"}}">
                <span class="zmdi-hc-stack zmdi-hc-lg">
                  <i class="zmdi zmdi-mic zmdi-hc-stack-1x"></i>
                  {% if not phoneuser.recording_enabled %}
                  <i class="zmdi zmdi-block zmdi-hc-stack-2x"></i>
                  {% endif %}
                </span>
                Registrazione
              </span>

            &nbsp;&nbsp;
            <span class="label {{phoneuser.listening_enabled|yesno:" green,red"}}">
                <span class="zmdi-hc-stack zmdi-hc-lg">
                  <i class="zmdi zmdi-headset zmdi-hc-stack-1x"></i>
                  {% if not phoneuser.listening_enabled %}
                  <i class="zmdi zmdi-block zmdi-hc-stack-2x"></i>
                  {% endif %}
                </span>
                Ascolto
              </span>
        </div>
        <h3 class="user">{{ phoneuser.last_name }} {{ phoneuser.first_name }}
       {% if phoneuser.four_bis_limited %}<small>(4bis limitato)</small>{% endif %}</h3>
        <div class="row">
            <div class="col-md-3">
                <h4 style="color:#666;">Codice: {{ phoneuser.pincode }}</h4>
            </div>
            <div class="col-md-3" style="text-align:center;">
                <h4 style="color:#666;">Matricola: {{ phoneuser.serial_no }}</h4>

            </div>
            <div class="col-md-3">
                <h4 style="color:#666;">Stato: {{ phoneuser.get_status_display | title }}</h4>
            </div>
            <div class="col-md-3" style="text-align:right;">
                <h4 style="color:#666;">Lingua: {{ phoneuser.get_language_display }}</h4>
            </div>
        </div>
    </div>
    <div class="card-action">
        <div class="row">
            {% if priv_anagrafica > 0 %}
                <div class="col-md-6">
                {% if phoneuser.enabled %}
                    <button class="btn green switchable" onClick="Phoneuser.changeStatus({{ phoneuser.id }}, 0)" data-help="Lo stato della scheda determina la possibilit&agrave; o meno di effettuare telefonate.">
                    <span class="status"><i class="zmdi zmdi-check"></i> SCHEDA ATTIVA</span>
                    <span class="action"><i class="zmdi zmdi-close"></i> DISATTIVA LA SCHEDA</span>
                    </button>
                {% else %}
                    <button class="btn red switchable" onClick="Phoneuser.changeStatus({{ phoneuser.id }}, 1)" data-help="Lo stato della scheda determina la possibilit&agrave; o meno di effettuare telefonate.">
                    <span class="status"><i class="zmdi zmdi-close"></i> SCHEDA DISATTIVA</span>
                    <span class="action"><i class="zmdi zmdi-check"></i> ATTIVA LA SCHEDA</span>
                    </button>
                {% endif %}
                </div>
                <div class="col-md-6" style="text-align:right;">
                    {% if priv_anagrafica > 1 %}
                    <button data-target="#myModal" class="btn btn-primary" onClick="Phoneuser.edit({{ phoneuser.id }})" tabindex="-1">
                    <i class="zmdi zmdi-edit"></i> Modifica
                    </button>&nbsp;&nbsp;
                    <button class="btn btn-info" onClick="Phoneuser.archive({{ phoneuser.id }})" tabindex="-1" data-help="Archiviazione di tutti i dati relativi alla anagrafica">
                    <i class="zmdi zmdi-archive"></i> Archivia
                    </button>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
    <input type="hidden" id="phoneuser-id" value="{{ phoneuser.id }}">
</div>

templates/phoneusers/whitelist_modal.html
 <!-- whitelist modal -->
 <div id="wh-modal" style="padding:15px;">
    <div class="form-inline control-group" style="margin-bottom:10px;" id="whitelist-label-div">
        <label style="text-align: right; width: 100px;margin-right:2px;">Etichetta:</label>
           <input type="text" class="input-medium prependedInput" placeholder="etichetta" name="etichetta" id="whitelist-label" value="{{ wl.label }}" {% if True %}disabled{% endif %}>
    </div>
    <div class="form-inline control-group" style="margin-bottom:10px;" id="whitelist-phonenumber-div">
        <label style="text-align: right; width: 100px;margin-right:2px;">Numero:</label>
           <input type="text" class="input-medium prependedInput" placeholder="numero" name="phonenumber" id="whitelist-phonenumber" value="{{ wl.phonenumber }}">
           <label class="muted whitelist-prefix-zone"></label>
    </div>
    <div class="form-inline control-group" style="margin-bottom:10px;" id="whitelist-duration-div">
        <label style="text-align: right; width: 100px;margin-right:2px;">Soglia:</label>
           <input type="text" class="input-mini prependedInput" placeholder="soglia" name="duration" id="whitelist-duration" value="{{ wl.duration }}"> 
           <label class="muted">minuti</label>
    </div>
    <div class="form-inline control-group" style="margin-bottom:10px;" id="whitelist-duration-div">
        <label style="text-align: right; width: 100px;margin-right:2px;">Tiplogia:</label>
           <select id="whitelist-frequency">
            <option value="0" {% if wl.frequency == 0 %}selected{% endif %}>Primo ingresso</option>
            <option value="1" {% if wl.frequency == 1 %}selected{% endif %}>Avvocato</option>
            {% if wl.phoneuser.four_bis_limited == 0 %}
                <option value="2" {% if wl.frequency == 2 %}selected{% endif %}>Ordinaria</option>
            {% else %}
                <option value="3" {% if wl.frequency == 3 %}selected{% endif %}>Ordinaria 4bis limitato</option>
            {% endif %}
           </select>
    </div>
    <div class="form-inline control-group hide" style="margin-bottom:10px;" id="whitelist-real-mobile-div">
    <label style="text-align: right; width: 100px;margin-right:6px;">Cellulare:</label>
      <input type="checkbox" id="whitelist-real-mobile" name="real_mobile" value="1" {% if wl.real_mobile %}checked{% endif %}> 
    </div>
     <br>
    <input type="hidden" name="phoneuser_id" id="whitelist-phoneuser-id" value="{{ phoneuser_id }}">
    <input type="hidden" name="whitelist_id" id="whitelist-id" value="{{ wl.id }}">
 </div>