cdrs/urls.py
from django.conf.urls import url
from .views import *
from archives.views import archive_cdrs_home

urlpatterns = [
   url(r'^cdrs/$', cdr_home),
   url(r'^cdrs/ajax/filter/$', cdr_items),
   url(r'^cdrs/changevalid/$', cdr_change_valid),
   url(r'^cdrs/export/excel/$', cdr_export_excel),
   #url(r'^cdrs/archives/(?P<archive_id>[0-9]*)$', archive_cdrs_home),
]

phonecab/urls.py
"""
General Url pattern
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
admin.autodiscover()

from phoneusers.urls import urlpatterns as phoneusers_urlpatterns
from prefs.urls import urlpatterns as prefs_urlpatterns
from cdrs.urls import urlpatterns as cdrs_urlpatterns
from records.urls import urlpatterns as records_urlpatterns
from profiles.urls import urlpatterns as profiles_urlpatterns
from audits.urls import urlpatterns as audits_urlpatterns
from archives.urls import urlpatterns as archives_urlpatterns
from tools.urls import urlpatterns as tools_urlpatterns
from logs.urls import urlpatterns as logs_urlpatterns

from phonecab.views import *

urlpatterns = [
    url(r'^$', phonecab_login),
    url(r'^login/$', phonecab_login),
    url(r'^logout/$', phonecab_logout),
    url(r'^phonecab/$', phonecab_realtime),
    url(r'^nightmode/$', phonecab_get_nightmode),
    url(r'^nightmode/(?P<mode>.*)$', phonecab_set_nightmode),

    url(r'^recordings/(?P<path>.*)$', serve,
        {'document_root': settings.RECORDS_ROOT}),

    url(r'^admin/doc/',
        include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += phoneusers_urlpatterns
urlpatterns += prefs_urlpatterns
urlpatterns += cdrs_urlpatterns
urlpatterns += records_urlpatterns
urlpatterns += profiles_urlpatterns
urlpatterns += audits_urlpatterns
urlpatterns += archives_urlpatterns
urlpatterns += tools_urlpatterns
urlpatterns += logs_urlpatterns

phoneusers/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^phoneusers/$', phoneuser_home),
    url(r'^phoneusers/new/$', phoneuser_edit),
    url(r'^phoneusers/view/(?P<phoneuser_id>[0-9]*)$', phoneuser_view),
    url(r'^phoneusers/edit/$', phoneuser_edit),
    url(r'^phoneusers/save/$', phoneuser_save),
    #url(r'^phoneusers/export/(?P<pincode>[0-9]*)$', phoneuser_export),
    url(r'^phoneusers/name/(?P<pincode>[0-9]*)$', phoneuser_name),
    url(r'^phoneusers/data/(?P<phoneuser_id>[0-9]*)$', phoneuser_data),
    url(r'^phoneusers/realtime/info/$', phoneuser_realtime_info),
    #url(r'^phoneusers/enable/(?P<phoneuser_id>[0-9]*)$', phoneuser_enable),
    #url(r'^phoneusers/disable/(?P<phoneuser_id>[0-9]*)$', phoneuser_disable),
    url(r'^phoneusers/changestatus/$', phoneuser_change_status),
    url(r'^phoneusers/check/pincode/$', phoneuser_check_pincode),
    url(r'^phoneusers/check/whitelist/$', phoneuser_check_whitelist),
    url(r'^phoneusers/archive/$', phoneuser_archive),
    url(r'^phoneusers/export/excel/$', phoneuser_export_excel),

    url(r'^whitelists/$', whitelist_items),
    url(r'^whitelists/edit/$', whitelist_edit),
    url(r'^whitelists/save/$', whitelist_save),
    url(r'^whitelists/remove/$', whitelist_remove),
    url(r'^whitelists/changestatus/$', whitelist_change_status),
    url(r'^whitelists/changeordinary/$', whitelist_change_ordinary),
    url(r'^whitelists/changeadditional/$', whitelist_change_additional),
    url(r'^whitelists/checkextra/$', whitelist_check_extra),
    #url(r'^whitelist/edit/(?P<whitelist_id>[0-9]*)$',
    # whitelist_edit),
    url(r'^credits/$', credit_items),
    url(r'^credits/new/$', credit_new),
    url(r'^credits/save/$', credit_save),
    url(r'^credits/print_recharge/(?P<credit_id>[0-9]*)$', credit_print_recharge),
    url(r'^credits/export/(?P<phoneuser_id>[0-9]*)$', credit_export),

]

phoneusers/models.py
import datetime
from django.db import models
from audits.models import Audit


class PhoneUser(models.Model):
    """
    Phoneuser

    Modella la scheda anagrafica.
    """

    ITALIAN = 'it'
    ENGLISH = 'en'
    FRENCH = 'fr'
    GERMAN = 'de'
    SPANISH = 'es'
    ARABIC = 'ar'

    LANGUAGES = (
        (ITALIAN, 'Italiano'),
        (ENGLISH, 'Inglese'),
        (FRENCH, 'Francese'),
        (GERMAN, 'Tedesco'),
        (SPANISH, 'Spagnolo'),
        (ARABIC, 'Arabo'),
    )

    STATO_NUOVO = 0
    STATO_IN_ATTESA = 1
    STATO_DEFINITIVO = 2

    STATI = (
        (STATO_NUOVO, 'nuovo arrivo'),
        (STATO_IN_ATTESA, 'in attesa di giudizio'),
        (STATO_DEFINITIVO, 'definitivo'),
    )

    first_name = models.CharField(max_length=35, verbose_name="nome")
    last_name = models.CharField(max_length=50, verbose_name="cognome")
    pincode = models.CharField(max_length=10, verbose_name="pin")
    serial_no = models.CharField(
        max_length=24, verbose_name="matricola", default='')
    listening_enabled = models.BooleanField(
        verbose_name="ascolto", default=False)
    recording_enabled = models.BooleanField(
        verbose_name="registrazione", default=False)
    covid_enabled = models.BooleanField(
        verbose_name="covid", default=False)
    enabled = models.BooleanField(verbose_name="stato", default=True)
    balance = models.DecimalField(
        verbose_name="credito residuo",
        default=0,
        max_digits=7,
        decimal_places=4)
    language = models.CharField(
        max_length=4, verbose_name="lingua", choices=LANGUAGES, default=ITALIAN)
    additional_calls = models.IntegerField(
        verbose_name="chiamate supplementari", default=0)
    additional_due_date = models.DateTimeField(
        verbose_name="scadenza chiamate supplementari", null=True)
    vipaccount = models.BooleanField(
        verbose_name="senza restizioni", default=False)
    four_bis_limited = models.BooleanField(
        verbose_name="4bis limitato", default=False)
    status = models.IntegerField(
        verbose_name="stato", choices=STATI, default=STATO_NUOVO)

    def get_full_name(self):
        return "%s %s" % (self.last_name, self.first_name)

    @staticmethod
    def get_from_pincode(pincode):
        items = PhoneUser.objects.filter(pincode=pincode)
        if items:
            return items[0]
        return None

    @staticmethod
    def get_from_serial_no(serial_no):
        items = PhoneUser.objects.filter(serial_no=serial_no)
        if items:
            return items[0]
        return None

    def __unicode__(self):
        return "%s %s (matricola %s codice %s)" % (self.last_name,
                                                   self.first_name,
                                                   self.serial_no,
                                                   self.pincode)


class Whitelist(models.Model):

    """
    Whitelist

    Modella i numeri che il phoneuser puo chiamare
    """

    ORDINARY_KIND = 0           # free
    SPECIAL_KIND = 1

    KINDS = (
        (ORDINARY_KIND, 'Ordinaria'),
        (SPECIAL_KIND, 'Primo ingresso'),
    )

    phoneuser = models.ForeignKey(PhoneUser)
    label = models.CharField(max_length=255, verbose_name="etichetta")
    phonenumber = models.CharField(max_length=40, verbose_name="telefono")
    duration = models.IntegerField(verbose_name="durata massima", default=600)
    kind = models.IntegerField(
        verbose_name="tipologia",
        choices=KINDS,
        default=ORDINARY_KIND)
    lawyer = models.BooleanField(
        verbose_name='avvocato',
        default=False)
    extraordinary = models.BooleanField(
        verbose_name='straordinaria',
        default=False)
    # definisce se un cellulare debba essere trattato come tale o come fisso
    real_mobile = models.BooleanField(
        verbose_name='cellulare',
        default=False)
    enabled = models.BooleanField(verbose_name="stato", default=False)
    additional = models.BooleanField(verbose_name="abilitazione a supplementari", default=False)

    def __unicode__(self):
        return "Numero %s (%s) relativo a %s" % (self.phonenumber,
            self.label,
            self.phoneuser,)


class Credit(models.Model):

    """
    Classe Credit

    Modella le ricariche effettuate dal phoneuser
    """
    phoneuser = models.ForeignKey(PhoneUser)
    recharge = models.DecimalField(
        verbose_name="ricarica", default=0, max_digits=5, decimal_places=2)
    recharge_date = models.DateTimeField(default=datetime.datetime.now)
    reason = models.CharField(max_length=255)

    @staticmethod
    def get_total(phoneuser):
        """Restituisce il totale delle ricariche effettuate"""
        total = Credit.objects.filter(phoneuser=phoneuser).aggregate(total=models.Sum('recharge'))
        return total['total']

templates/phoneusers/whitelists/table.html
{% load phonecabtags %}
{% load tz %}
<div class="card bordered">
  <div class="card-header">
    {% if priv_whitelist > 1 %}
    <button class="action btn btn-primary btn-sm" onClick="Whitelist.edit(0)">
      <i class="zmdi zmdi-plus"></i>
      Nuova Autorizzazione</button>
    {% endif %}
    <span class="card-title">
      <i class="zmdi zmdi-format-list-numbered"></i>
      Numeri Autorizzati</span>
  </div>
  <div class="table-responsive white">
    <table class="table table-striped table-full table-full-small">
      <thead>
        <tr>
          <th style="width:40px;">Stato</th>
          <th style="width:auto;">Etichetta</th>
          <th style="width:180px;text-align:center;">Numero</th>
          <th style="width:30px; text-align:center;">Avvocato</th>
          <th style="width:120px; text-align:center;">Vincolo 15gg</th>
          <th style="width:160px; text-align:center;">Tipologia</th>
          <th style="width:30px; text-align:center;">Straordinaria</th>
          <th style="width:30px; text-align:center;">Supplementare</th>
          <th class="noprint" style="width:120px; text-align:center;">Azioni</th>
        </tr>
      </thead>
      <tbody>
        {% for wl in whitelists %}
        <tr>
          <td style="text-align:center;">
            {% if wl.enabled %}
              {% if priv_whitelist > 0 %}
                <button class="btn btn-xs btn-success" onClick="Whitelist.changeStatus({{ wl.id }},0)" title="Premi per disabilitare l&apos;autorizzazione" {% if forloop.first %}data-help="Lo stato della scheda determina la possibilit&agrave; o meno di effettuare telefonate."{% endif %}>
                  <i class="zmdi zmdi-check"></i>
                </button>
                <i class="zmdi zmdi-check print-only"></i>
              {% else %}
                <i class="zmdi zmdi-check"></i>
              {% endif %}
            {% else %}
              {% if priv_whitelist > 0 %}
                <button class="btn btn-xs btn-danger" onClick="Whitelist.changeStatus({{ wl.id }},1)" title="Premi per abilitare l&apos;autorizzazione" {% if forloop.first %}data-help="Lo stato della scheda determina la possibilit&agrave; o meno di effettuare telefonate."{% endif %}>
                  <i class="zmdi zmdi-close"></i>
                </button>
                <i class="zmdi zmdi-close print-only"></i>
              {% else %}
                <i class="zmdi zmdi-close"></i>
              {% endif %}
            {% endif %}
          </td>
          <td>{{ wl.label }}</td>
          <td style="text-align:center;">{{ wl.phonenumber }}</td>
          <td style="text-align:center;">{{ wl.lawyer|yesno:"Si,No"  }}</td>
          <td style="text-align:center;">{{ wl.real_mobile|yesno:"Si,No" }}</td>
          <!--<td style="text-align:center;">{{ wl.duration|format_time }}</td>-->
          <td style="text-align:center;">{{ wl.get_kind_display }}</td>
          <td style="text-align:center;">
          {% if wl.kind == 0 %}
            {% if wl.extraordinary %}
              {% if priv_whitelist > 0 %}
                <button class="btn btn-xs btn-success" onClick="Whitelist.changeOrdinary({{ wl.id }},0)" title="Premi per rendere ordinaria" {% if forloop.first %}data-help="La disabilitazione alle chiamate straordinarie preclude la possibilit&agrave; di effettuare chiamate senza vincoli legati alle chiamate effettuate in precedenza."{% endif %}>
                  <i class="zmdi zmdi-check"></i>
                </button>
                <i class="zmdi zmdi-check print-only"></i>
              {% else %}
                <i class="zmdi zmdi-check"></i>
              {% endif %}
            {% else %}
              {% if priv_whitelist > 0   %}
                <button class="btn btn-xs btn-danger" onClick="Whitelist.changeOrdinary({{ wl.id }},1)" title="Premi per rendere straordinaria" {% if forloop.first %}data-help="L'abilitazione alle chiamate straordinarie determina la possibilit&agrave; di effettuare chiamate senza vincoli legati alle chiamate effettuate in precedenza."{% endif %}>
                  <i class="zmdi zmdi-close"></i>
                </button>
                <i class="zmdi zmdi-close print-only"></i>
              {% else %}
                <i class="zmdi zmdi-close"></i>
              {% endif %}
            {% endif %}
          {% endif %}
          </td>
          <td style="text-align:center;">
            {% if wl.additional %}
              {% if priv_whitelist > 0 %}
                <button class="btn btn-xs btn-success" onClick="Whitelist.changeAdditional({{ wl.id }},0)" title="Premi per rendere non contattabile con chiamata supplementare" {% if forloop.first %}data-help="La disabilitazione alle chiamate suplementari preclude la possibilit&agrave; effettuare chiamate verso questa utenza in tale regime."{% endif %}>
                  <i class="zmdi zmdi-check"></i>
                </button>
                <i class="zmdi zmdi-check print-only"></i>
              {% else %}
                <i class="zmdi zmdi-check"></i>
              {% endif %}
            {% else %}
              {% if priv_whitelist > 0   %}
                <button class="btn btn-xs btn-danger" onClick="Whitelist.changeAdditional({{ wl.id }},1)" title="Premi per rendere contattabile con chiamata supplementare" {% if forloop.first %}data-help="L'abilitazione alle chiamate supplementari determina la possibilit&agrave; di effettuare chiamate verso questa utenza in tale regime."{% endif %}>
                  <i class="zmdi zmdi-close"></i>
                </button>
                <i class="zmdi zmdi-close print-only"></i>
              {% else %}
                <i class="zmdi zmdi-close"></i>
              {% endif %}
            {% endif %}
          </td>
          <td class="noprint" style="text-align:center;">
            {% if priv_whitelist > 1 %}
            <button class="btn btn-sm btn-default" onClick="Whitelist.edit({{ wl.id }}, {{ wl.phoneuser.id }})" title="Premi per modificare l&apos;autorizzazione">
              <i class="zmdi zmdi-edit"></i>
            </button>
            <button class="btn btn-sm btn-default" onClick="Whitelist.remove({{ wl.id }})" title="Premi per eliminare l&apos;autorizzazione">
              <i class="zmdi zmdi-delete"></i>
            </button>
            {% endif%}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

templates/phoneusers/whitelists/whitelist.html
 <!-- whitelist modal -->
<form class="form-horizontal placeholder-form" novalidate="true">
<fieldset>
  <div class="form-group">
    <label for="first-name" class="col-xs-4 control-label">Etichetta</label>
    <div class="col-xs-6 filled">
      <input type="text" class="form-control input-small" id="whitelist-label" placeholder="Etichetta" value="{{ whitelist.label }}" required>
    </div>
  </div>
  <div class="form-group">
    <label for="first-name" class="col-xs-4 control-label">Numero</label>
    <div class="col-xs-5 filled">
      <input type="text" class="form-control input-small" id="whitelist-phonenumber" placeholder="Numero" value="{{ whitelist.phonenumber }}" required>
      <span class="whitelist-check hide" style="color: red;">Gi&agrave; associato</span>
    </div>
  </div>
  <div class="form-group">
    <label for="first-name" class="col-xs-4 control-label">Soglia</label>
    <div class="col-xs-2 filled">
      <input type="text" class="form-control input-small" id="whitelist-duration" placeholder="Soglia" value="{{ whitelist.duration }}" required{% if not change_threshold  == "1" %} disabled{% endif %}>
      <label class="muted">minuti</label>
    </div>
  </div>
  <div class="form-group">
    <label class="col-xs-4 control-label">Tipologia</label>
    <div class="col-xs-5">
      <select class="select2 form-control select2-hidden-accessible" tabindex="-1" aria-hidden="true" id="whitelist-kind">
        <option value="0" {% if whitelist.kind == 0 %}selected{% endif %}>Ordinaria</option>
        {% if enable_first_in == "1" %}
        <option value="1" {% if whitelist.kind == 1 %}selected{% endif %}>Primo ingresso</option>
        {% endif %}
      </select>
    </div>
  </div>
  <div class="form-group" id="whitelist-layer-element">
    <label for="enabled" class="col-xs-4 control-label">Avvocato</label>
    <div class="col-xs-4">
      <div class="checkbox">
        <label class="filled">
          <input type="checkbox" {% if whitelist.lawyer %}checked="checked"{% endif %} id="whitelist-lawyer"></label>
      </div>
    </div>
  </div>
  <div class="form-group" id="whitelist-real-mobile-element">
    <label for="enabled" class="col-xs-4 control-label">Vincolo 15gg</label>
    <div class="col-xs-4">
      <div class="checkbox">
        <label class="filled">
          <input type="checkbox" {% if whitelist.real_mobile %}checked="checked"{% endif %} id="whitelist-real-mobile"></label>
      </div>
    </div>
  </div>
  <div class="form-group" id="whitelist-enable-additional-element">
    <label for="whitelist-additional" class="col-xs-4 control-label">Supplementare</label>
    <div class="col-xs-4">
      <div class="checkbox">
        <label class="filled">
          <input type="checkbox" {% if whitelist.additional %}checked="checked"{% endif %} id="whitelist-additional"></label>
      </div>
    </div>
  </div>
  <input type="hidden" name="phoneuser_id" id="whitelist-phoneuser-id" value="{{ phoneuser_id }}">
  <input type="hidden" name="whitelist_id" id="whitelist-id" value="{{ whitelist.id }}">

 </fieldset>
 </form>